/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/DashboardView/components/AppCard/AppCard': RouteRecordInfo<'/DashboardView/components/AppCard/AppCard', '/DashboardView/components/AppCard/AppCard', Record<never, never>, Record<never, never>>,
    '/DashboardView/components/AppCard/NotExistCard': RouteRecordInfo<'/DashboardView/components/AppCard/NotExistCard', '/DashboardView/components/AppCard/NotExistCard', Record<never, never>, Record<never, never>>,
    '/DashboardView/components/AppForm/AppFormContent': RouteRecordInfo<'/DashboardView/components/AppForm/AppFormContent', '/DashboardView/components/AppForm/AppFormContent', Record<never, never>, Record<never, never>>,
    '/DashboardView/components/AppForm/AppFormDrawer': RouteRecordInfo<'/DashboardView/components/AppForm/AppFormDrawer', '/DashboardView/components/AppForm/AppFormDrawer', Record<never, never>, Record<never, never>>,
    '/DashboardView/components/DeleteConfirm/DeleteConfirmContent': RouteRecordInfo<'/DashboardView/components/DeleteConfirm/DeleteConfirmContent', '/DashboardView/components/DeleteConfirm/DeleteConfirmContent', Record<never, never>, Record<never, never>>,
    '/DashboardView/components/DeleteConfirm/DeleteConfirmDrawer': RouteRecordInfo<'/DashboardView/components/DeleteConfirm/DeleteConfirmDrawer', '/DashboardView/components/DeleteConfirm/DeleteConfirmDrawer', Record<never, never>, Record<never, never>>,
    '/DashboardView/DashboardView': RouteRecordInfo<'/DashboardView/DashboardView', '/DashboardView/DashboardView', Record<never, never>, Record<never, never>>,
    '/LoginView/components/FormView': RouteRecordInfo<'/LoginView/components/FormView', '/LoginView/components/FormView', Record<never, never>, Record<never, never>>,
    '/LoginView/components/SecurityText': RouteRecordInfo<'/LoginView/components/SecurityText', '/LoginView/components/SecurityText', Record<never, never>, Record<never, never>>,
    '/LoginView/LoginView': RouteRecordInfo<'/LoginView/LoginView', '/LoginView/LoginView', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/DashboardView/components/AppCard/AppCard.vue': {
      routes: '/DashboardView/components/AppCard/AppCard'
      views: never
    }
    'src/pages/DashboardView/components/AppCard/NotExistCard.vue': {
      routes: '/DashboardView/components/AppCard/NotExistCard'
      views: never
    }
    'src/pages/DashboardView/components/AppForm/AppFormContent.vue': {
      routes: '/DashboardView/components/AppForm/AppFormContent'
      views: never
    }
    'src/pages/DashboardView/components/AppForm/AppFormDrawer.vue': {
      routes: '/DashboardView/components/AppForm/AppFormDrawer'
      views: never
    }
    'src/pages/DashboardView/components/DeleteConfirm/DeleteConfirmContent.vue': {
      routes: '/DashboardView/components/DeleteConfirm/DeleteConfirmContent'
      views: never
    }
    'src/pages/DashboardView/components/DeleteConfirm/DeleteConfirmDrawer.vue': {
      routes: '/DashboardView/components/DeleteConfirm/DeleteConfirmDrawer'
      views: never
    }
    'src/pages/DashboardView/DashboardView.vue': {
      routes: '/DashboardView/DashboardView'
      views: never
    }
    'src/pages/LoginView/components/FormView.vue': {
      routes: '/LoginView/components/FormView'
      views: never
    }
    'src/pages/LoginView/components/SecurityText.vue': {
      routes: '/LoginView/components/SecurityText'
      views: never
    }
    'src/pages/LoginView/LoginView.vue': {
      routes: '/LoginView/LoginView'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
